config/routes.rb
Rails.application.routes.draw do
  root 'revenue#revenue'
  resources :sales, only: :index
  resources :goods
  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      sessions: 'api/devise_token_auth/sessions'
    }
    resources :goods do
      member do
        get 'sales'
        get 'sales/:sale_id', to: 'goods#sale'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/good.rb
require 'roo'
class Good < ApplicationRecord
  # relations
  has_many :sales, -> { order(:date_of_sale) },
           dependent: :destroy,
           inverse_of: :good
  # nested_attributes
  accepts_nested_attributes_for :sales,
                                allow_destroy: true, reject_if: :all_blank
  # validations
  validates :title, presence: true, uniqueness: true
  # class methods
  def self.seed
    return true if Good.first

    xlsx = Roo::Excelx.new(
      Rails.root.join('app', 'files', 'xlsx', 'Test task goods.xlsx')
    )
    header = nil
    xlsx.each_row_streaming do |row|
      if header.blank?
        header = row.map(&:value)
      else
        good = nil
        sales = []
        row.each_with_index do |cell, index|
          if good.blank?
            good = cell.value
            return true if good.blank?
          else
            sales.push(date_of_sale: header[index], price: cell.value)
          end
        end
        Good.create!(title: good).sales.create!(sales) if sales.present?
      end
    end
  end
end

app/controllers/api/goods_controller.rb
class Api::GoodsController < Api::ApiController
  before_action :authenticate_api_user!, only: %i[create update destroy]
  before_action :set_good, only: %i[show edit update destroy sales sale]

  # GET /api/goods
  def index
    @goods = Good.order(:title)
  end

  # GET /api/goods/1
  def show; end

  # GET /api/goods/new
  def new
    @good = Good.new
  end

  # GET /api/goods/1/edit
  def edit; end

  # POST /api/goods
  def create
    @good = Good.new(good_params)
    unless @good.valid?
      return render json: @good.errors, status: :unprocessable_entity
    end

    Good.transaction do
      return render :show, status: :created if @good.save && add_new_good_params

      raise ActiveRecord::Rollback
    end
    render json: @good.errors, status: :unprocessable_entity
  end

  # PATCH/PUT /api/goods/1
  def update
    Good.transaction do
      if @good.update(good_params) && update_good_params
        return render :show, status: :ok
      end

      raise ActiveRecord::Rollback
    end
    render json: @good.errors, status: :unprocessable_entity
  end

  # DELETE /api/goods/1
  def destroy
    @good.destroy
    head :no_content
  end

  # GET /api/goods/:id/sales
  def sales
    @sales = @good.sales
  end

  # GET /api/goods/:id/sales/:sale_id
  def sale
    @sale = @good.sales.find(params[:sale_id])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_good
    @good = Good.find(params[:id])
  end

  # Never trust parameters from the scary internet
  def good_params
    params.permit(:title)
  end

  def sale_params
    params.permit(sales: %i[id date_of_sale price _destroy])
  end

  def add_new_good_params
    new_params = sale_params[:sales]
    return true if new_params.blank?

    @good.sales.create(new_params)
    @good.valid?
  end

  def update_good_params
    new_params = sale_params[:sales]
    return true if new_params.blank?

    begin
      new_params.each do |param|
        id = param[:id]
        if id.blank?
          @good.sales.create!(
            date_of_sale: param[:date_of_sale],
            price: param[:price]
          )
        else
          sale = @good.sales.find(id)
          if param[:_destroy]
            @good.sales.destroy sale
          else
            sale.update!(
              date_of_sale: param[:date_of_sale],
              price: param[:price]
            )
          end
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      @good.errors.add(:error, e)
      return false
    rescue ActiveRecord::RecordInvalid => e
      @good.errors.add(:error, e)
      return false
    end
    true
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: %i[show edit update destroy]

  # GET /goods
  def index
    @goods = Good.order(:title)
  end

  # GET /goods/1
  def show; end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit; end

  # POST /goods
  def create
    @good = Good.new(good_params)
    return render :new unless @good.valid?

    if @good.save && add_new_good_params
      redirect_to @good, notice: t('.success')
    else
      render :new
    end
  end

  # PATCH/PUT /goods/1
  def update
    if @good.update(good_params) && add_new_good_params
      redirect_to @good, notice: t('.success')
    else
      render :edit
    end
  end

  # DELETE /goods/1
  def destroy
    @good.destroy
    redirect_to goods_url, notice: t('.success')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_good
    @good = Good.find(params[:id])
  end

  # Never trust parameters from the scary internet
  def good_params
    params.require(:good).permit(
      :title, sales_attributes: %i[id date_of_sale price _destroy]
    )
  end

  def new_good_params
    params.require(:good).permit(new_sales_attributes: %i[date_of_sale price])
  end

  def add_new_good_params
    new_params = new_good_params
    return true if new_params.blank?

    @good.sales.create(new_params[:new_sales_attributes].values.map(&:to_h))
    @good.valid?
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<%= form_with(model: good, local: true) do |form| %>
  <% if @good.errors.any? %>
    <%= render partial:'partials/notice', locals:{notice: good.errors.values.flatten.join('<br>'), type: 'error'} %>
  <% end %>
  
  <div class="actions" layout="row" layout-align="space-between center">
    <div layout="row" layout-align="start center">
      <%= form.label :title, class: 'title-label' %>
      <%= form.text_field :title, class: 'title-input' %>
    </div>
    <%= form.submit %>
  </div>
  <table class="table">
    <thead>
    <tr>
      <th>Date</th>
      <th>Price</th>
      <th>Delete</th>
    </tr>
    </thead>
    
    <tbody>
    <%= form.fields_for :sales do |sales_form| %>
      <tr>
        <td><%= sales_form.text_field :date_of_sale, class: 'value-input' %></td>
        <td><%= sales_form.text_field :price, class: 'value-input' %></td>
        <td><%= sales_form.check_box :_destroy %></td>
      </tr>
    <% end %>
    <tr ng-repeat="new_sales in new_sales_attributes">
      <td><input class="value-input" type="text" value="" name="good[new_sales_attributes][{{new_sales}}][date_of_sale]" ></td>
      <td><input class="value-input" type="text" value="" name="good[new_sales_attributes][{{new_sales}}][price]" ></td>
      <td><md-icon class="delete-sale" ng-click="delete(new_sales)"> close </md-icon></td>
    </tr>
    </tbody>
  </table>
<% end %>
<button class="add-sale" ng-click="add()">Add Sale</button>

app/views/goods/edit.html.erb
<div class="goods" ng-controller="GoodsCtrl">
  <h1>Editing Good</h1>
  <%= link_to 'Show', @good, class:'navigation' %>
  <%= link_to 'List', goods_path, class:'navigation' %>
  <%= link_to 'Revenue', root_path, class:'navigation' %>
  <%= render 'form', good: @good %>
</div>

app/views/goods/index.html.erb
<div class="goods" ng-controller="GoodsCtrl">
  <% if notice.present? %>
    <%= render partial:'partials/notice', locals:{notice: notice, type: 'success'} %>
  <% end %>
  <h1>Goods</h1>
  <%= link_to 'New Good', new_good_path, class:'navigation' %>
  <%= link_to 'Revenue', root_path, class:'navigation' %>
  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Controls</th>
    </tr>
    </thead>
    
    <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%=good.title%></td>
        <td>
          <%= link_to 'Show', good, class:'navigation'%>
          <%= link_to 'Edit', edit_good_path(good) , class:'navigation'%>
          <%= link_to 'Destroy', good, method: :delete, class:'navigation', 'ng-click': 'destroy_good($event)'%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/goods/new.html.erb
<div class="goods" ng-controller="GoodsCtrl">
  <h1>New Good</h1>
  <%= link_to 'List', goods_path, class:'navigation' %>
  <%= link_to 'Revenue', root_path, class:'navigation' %>
  <%= render 'form', good: @good %>
</div>

app/views/goods/show.html.erb
<div class="goods">
  <% if notice.present? %>
    <%= render partial:'partials/notice', locals:{notice: notice, type: 'success'} %>
  <% end %>
  <h1><%= @good.title %></h1>
  <%= link_to 'Edit', edit_good_path(@good), class:'navigation' %>
  <%= link_to 'List', goods_path, class:'navigation' %>
  <%= link_to 'Revenue', root_path, class:'navigation' %>
  <table class="table">
    <thead>
    <tr>
      <th>Date</th>
      <th>Price</th>
    </tr>
    </thead>
    
    <tbody>
    <% @good.sales.each do |sale| %>
      <tr>
        <td><%=sale.date_of_sale%></td>
        <td><%=sale.price%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>